package com.onlinefood.entities;

public enum StatusType {
	
	PENDING,CONFIRMED,PREPARING,COOKING,READY_FOR_PICKUP,OUT_FOR_DELIVERY,DELIVERED,CANCELLED,DELAYED,COMPLETED,PAYMENT_DONE,ON_HOLD,REVIEW,ARCHIVE
	
}
